### ISSUE TITLE
USB TIMEOUT

### ISSUE THREAD

**Issue by evarasv1** [vimu-tech/VmMsoSDK#1]
Hello, when i read the data using two channels

Capture(mem_length / 1024, 3, 0);

i see this error in a loop runing

**********Capture channel 3 8192 KB**********
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_TIMEOUT]!

**Comment by vimu-tech** [comment]
Hello, there are some arm64 systems that cannot allocate large memory. You can try to modify the collection length to see if the collection is normal.

**Comment by evarasv1** [comment]
this is my while loop to colects data
void USBHandler::run()
{

	        // ... lÃ³gica relacionada con el USB (transfiere el contenido de run_program aquÃ­)

		  // Todo el cÃ³digo que estaba en main() ahora estarÃ¡ aquÃ­
    
			std::cout << "Vdso Test..." << std::endl;

			InitDll(1, 1);
			std::this_thread::sleep_for(std::chrono::milliseconds(500));
			SetDevNoticeCallBack(this, StaticDevNoticeAddCallBack, StaticDevNoticeRemoveCallBack);
			SetDataReadyCallBack(this, StaticDevDataReadyCallBack);

			while (true)
			{
				// Chequeo de guardado
				if (needToSave) {
					this->saveData(this->dataHistory1, this->additionalDataHistory1, "datos_canal_0.txt");
					this->saveData(this->dataHistory2, this->additionalDataHistory2, "datos_canal_1.txt");
					needToSave = false; // Resetear la bandera
				}



				while(runing)
				{

					std::this_thread::sleep_for(std::chrono::milliseconds(300));
					
					if(IsDevAvailable())
					{
						if (IsDataReady())
						{
							unsigned int len = ReadVoltageDatas(0, buffer, mem_length);
							unsigned int len2 = ReadVoltageDatas(1, buffer2, mem_length); // Canal 2

							            // Llama a checkThreshold para verificar si algÃºn valor en el buffer supera el umbral


							if (!thresholdExceeded) {
								checkThreshold(len, buffer);
								if (thresholdExceeded) {
									std::cout << "PICO DETECTADO" << std::endl;
								}
							}

							if (thresholdExceeded) {
								additionalDataHistory1.push_back(std::vector<double>(buffer, buffer + len));
								additionalDataHistory2.push_back(std::vector<double>(buffer2, buffer2 + len2));
							} else {
								dataHistory1[currentPosition] = std::vector<double>(buffer, buffer + len);
								dataHistory2[currentPosition] = std::vector<double>(buffer2, buffer2 + len2);
							}

							// Incrementa el contador de ciclos solo si se ha superado el umbral
							if (thresholdExceeded) {
								cycleCount++;

								std::cout << "Ciclo" << cycleCount << std::endl;
								// Avanza la posiciÃ³n solo si se ha superado el umbral
								currentPosition = (currentPosition + 1) % dataHistory1.size();
							}

							// Detiene el ciclo si se han almacenado 12 buffers tras superar el umbral
							if (thresholdExceeded && cycleCount >= 20) {
								runing = false;
								socketHandler->emitRunningStatus(runing);
							}

							Capture(mem_length / 1024, 3, 0);
						}
					}

					


				}
			};
    
}

**Comment by vimu-tech** [comment]
“additionalDataHistory1.push_back(std::vector<double>(buffer, buffer + len));”
If you need to save historical ingestion data, each of your buffers needs to be allocated with new.

You can just run our dlltest example and see if it succeeds. After success, you can add the historical data saving function to the dlltest example

**Comment by evarasv1** [comment]
I have attempted to use the trigger but the device captures data even when the voltage threshold of the rising edge type has not been exceeded:
// setting up trigger
SetTriggerMode(0x00);
SetTriggerStyle(0x01);
SetTriggerSource(0x00);
SetTriggerLevel(500);
SetPreTriggerPercent(75);

Is the Capture method always fetching ADC data? Isn't it working as an interrupt?

**Comment by vimu-tech** [comment]
Hello, i change the dlltest add the trigger setting and add channel buffer for every channel. 
Capture funtion is only capture once, after you read the datas, you need call capture again.

#include "DllTest.h"
#include "VmMsoLib.h"
#include <thread>

//////////////////////////////////////////////////////////////////
//caputer channel num 
#define CAPTURE_CHN_NUM 2
//using callback read datas ?
#define DATA_READ_CALLBACK_MODE 1

//////////////////////////////////////////////////////////////////
//bool runing = true;
int sample_num = 0;
unsigned int* sample = NULL;
unsigned int mem_length = 0;

double* buffer_ch1 = NULL;
#if (CAPTURE_CHN_NUM == 2)
double* buffer_ch2 = NULL;
#endif

void ReadDatas()
{
	unsigned int len = ReadVoltageDatas(0, buffer_ch1, mem_length);
                
	double minv=buffer_ch1[0];
	double maxv=buffer_ch1[0];
	for(unsigned int i=0; i<len; i++)
	{
		minv = buffer_ch1[i]<minv? buffer_ch1[i]:minv;
		maxv = buffer_ch1[i]>maxv? buffer_ch1[i]:maxv;
	}
	std::cout << "Channel 1 ReadVoltageDatas " << len <<" minv " << minv << " maxv " << maxv << '\n';

#if (CAPTURE_CHN_NUM == 2)
	len = ReadVoltageDatas(1, buffer_ch2, mem_length);
                
	minv=buffer_ch2[0];
	maxv=buffer_ch2[0];
	for(unsigned int i=0; i<len; i++)
	{
		minv = buffer_ch2[i]<minv? buffer_ch2[i]:minv;
		maxv = buffer_ch2[i]>maxv? buffer_ch2[i]:maxv;
	}
	std::cout << "Channel 2 ReadVoltageDatas " << len <<" minv " << minv << " maxv " << maxv << '\n';
#endif
}

void NextCapture()
{
	//change  trigger
	//SetTriggerMode(0x00);  //TRIGGER_MODE_AUTO 0
	//SetTriggerMode(0x01);  //TRIGGER_MODE_LIANXU 1
	//SetTriggerStyle(0x01);  //TRIGGER_STYLE_RISE_EDGE
	//SetTriggerSource(0x00);  //TRIGGER_SOURCE_CH1
	SetTriggerLevel(500); //500mv
	//SetPreTriggerPercent(75);

	//std::this_thread::sleep_for(std::chrono::milliseconds(100));
#if (CAPTURE_CHN_NUM == 2)
	int real_len = Capture(mem_length/1024, 3, 0);
#else
	int real_len = Capture(mem_length/1024, 1, 0);
#endif
	std::cout << "Capture " << real_len * 1024 << '\n';
}

void CALLBACK DevDataReadyCallBack(void* ppara)
{
	std::cout << "DevDataReadyCallBack\n";
#ifdef DATA_READ_CALLBACK_MODE
	ReadDatas();
	NextCapture();
#endif	
}

void CALLBACK DevNoticeAddCallBack(void* ppara)
{
    std::cout << "DevNoticeAddCallBack\n";
	//sample
	int sample_num = GetOscSupportSampleNum();
	if (sample != NULL)
	{
		delete[]sample;
		sample = NULL;
	}
	sample = new unsigned int[sample_num];
	if (GetOscSupportSamples(sample, sample_num))
	{
		for (int i = 0; i < sample_num; i++)
			std::cout << sample[i] << '\n';
		std::cout << std::endl;
	}
	SetOscSample(sample[sample_num-2]);

	// setting up trigger
	//SetTriggerMode(0x00);  //TRIGGER_MODE_AUTO 0
	SetTriggerMode(0x01);  //TRIGGER_MODE_LIANXU 1
	SetTriggerStyle(0x01);  //TRIGGER_STYLE_RISE_EDGE
	SetTriggerSource(0x00);  //TRIGGER_SOURCE_CH1
	SetTriggerLevel(500); //500mv
	SetPreTriggerPercent(50);

	//
#if (CAPTURE_CHN_NUM == 2)
	mem_length =  GetMemoryLength()*1024 / 2;  //KB
	if (buffer_ch1 != NULL)
		delete[]buffer_ch1;
	buffer_ch1 = new double[mem_length];

	if (buffer_ch2 != NULL)
		delete[]buffer_ch2;
	buffer_ch2 = new double[mem_length];

	if((buffer_ch1!=NULL)&&(buffer_ch2!=NULL))
		NextCapture();
	else
		std::cout << "new menory failed!" << std::endl;
#else
	mem_length =  GetMemoryLength()*1024;  //KB
	if (buffer_ch1 != NULL)
		delete[]buffer_ch1;
	buffer_ch1 = new double[mem_length];

	if(buffer_ch1!=NULL)
		NextCapture();
	else
		std::cout << "new menory failed!" << std::endl;
#endif
}

void CALLBACK DevNoticeRemoveCallBack(void* ppara)
{
     std::cout << "DevNoticeRemoveCallBack\n";
	 /*runing = false;
	sample_num = 0;
	if (sample != NULL)
	{
		delete[]sample;
		sample = NULL;
	}

	if (buffer != NULL)
	{
		delete[]buffer;
		buffer = NULL;
	}*/
}

int main()
{
	std::cout << "Vdso Test..." << std::endl;

	InitDll(1, 1);
	std::this_thread::sleep_for(std::chrono::milliseconds(500));
	SetDevNoticeCallBack(NULL, DevNoticeAddCallBack, DevNoticeRemoveCallBack);
	SetDataReadyCallBack(NULL, DevDataReadyCallBack);
	
	while (true)
	{
#ifndef DATA_READ_CALLBACK_MODE
		std::this_thread::sleep_for(std::chrono::milliseconds(1000));
        if(IsDevAvailable())
        {
            if (IsDataReady())
            {
				ReadDatas();
				NextCapture();
            }
        }
#endif	
	};

	FinishDll();
	std::cout << "...Vdso Test" << std::endl;
	return 0;
}

**Comment by vimu-tech** [comment]
We have updated the entire library and DLLTest, you can clone the latest version and test the features of DLLTest directly.

**Comment by evarasv1** [comment]
Thanks
I see that in the uploaded code, the trigger switches to mode 0, which is to have data on each capture regardless of the voltage level at the input. However, if I switch to mode 1, I wouldn't have any problems capturing data except that data will only be available when the trigger threshold is exceeded, is that correct?

scss
Copy code
// setting up trigger
SetTriggerMode(0x00);  //TRIGGER_MODE_AUTO 0
//SetTriggerMode(0x01);  //TRIGGER_MODE_LIANXU 1
SetTriggerStyle(0x01);  //TRIGGER_STYLE_RISE_EDGE

**Comment by vimu-tech** [comment]
Yes. 
SetTriggerMode(0x00); The hardware will have a timer, and if the timer is exceeded, it will be automatically collected once.
SetTriggerMode(0x01); The hardware waits for the trigger conditions you set to be met before collecting

**Comment by evarasv1** [comment]
The DLLtest code occasionally returns this:

InitDll.............. Log=1 Watchdog=1
**********UsbDevAddRemoveCallBack DEVICE_NOTICE_ID=1**********
**********CreateOscDevice 1**********
**********CreateDdsDevice failed**********
**********CreateIODevice MSO21AL(1.0)(  )  94022870**********
**********CreateIODevice Success**********
**********SetDevNoticeCallBack**********
**********SetDataReadyCallBack**********
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
DevNoticeAddCallBack
**********GetOscSupportSampleNum num=16**********
**********GetOscSupportSamples num=16**********
1000
2000
5000
10000
20000
50000
100000
200000
500000
1000000
2000000
5000000
10000000
20000000
50000000
100000000

**********SetOscSample 20000000**********
**********SetTriggerMode 1**********
**********SetTriggerStyle 1**********
**********SetTriggerSource 0**********
**********SetChufaDianPing 1900**********
**********SetPreTriggerPercent 50**********
**********SetOscChannelRange 0 -10000 10000**********
**********SetOscChannelRange 1 -10000 10000**********
**********GetMemoryLength 8192 KB**********
COUNT =1
**********Capture channel 3 1024 KB**********
Capture 1048576
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
**********UsbDevAddRemoveCallBack DEVICE_NOTICE_ID=1**********
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlOut libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!
WinUsbDevMSO2021::CtrlIn libusb_bulk_transfer Failed:[LIBUSB_ERROR_NO_DEVICE]!


Is there a way to correct or re-read the USB when this occurs?

**Comment by vimu-tech** [comment]
Please update the SharedLibrary,  last commit have fix the re-read the USB bug. 
New SharedLibrary+DLLtest can auto destory the removed device and re connect. 
If you update the library and it still doesn't work, please let me know.
